name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build matchstick
        run: npm run test:build
      - name: Run tests
        run: npm run test:unit
      - name: Collect coverage
        run: npm run test:coverage
