name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm run test && npm run test:unit
